#!/usr/bin/env node

const Reset = "\x1b[0m";
const Bright = "\x1b[1m";
const Dim = "\x1b[2m";
const Underscore = "\x1b[4m";
const Blink = "\x1b[5m";
const Reverse = "\x1b[7m";
const Hidden = "\x1b[8m";

const FgBlack = "\x1b[30m";
const FgRed = "\x1b[31m";
const FgGreen = "\x1b[32m";
const FgYellow = "\x1b[33m";
const FgBlue = "\x1b[34m";
const FgMagenta = "\x1b[35m";
const FgCyan = "\x1b[36m";
const FgWhite = "\x1b[37m";

const BgBlack = "\x1b[40m";
const BgRed = "\x1b[41m";
const BgGreen = "\x1b[42m";
const BgYellow = "\x1b[43m";
const BgBlue = "\x1b[44m";
const BgMagenta = "\x1b[45m";
const BgCyan = "\x1b[46m";
const BgWhite = "\x1b[47m";

async function getCovidData() {
  return new Promise((resolve, reject) => {
    const https = require('https');
    https.get("https://covidtracking.com/api/us/daily", (resp) => {
      let data = '';
      resp.on('data', (chunk) => {
        data += chunk;
      });
      resp.on('end', () => {
        try {
          resolve(JSON.parse(data));
        } catch(e) {
          reject(e);
        }
      });
    }).on("error", reject);
  });
}

async function report() {
  const d = await getCovidData();

  const mostRecentDay = d[d.length - 1];
  const dayBeforeMostRecent = d[d.length - 2];
  const twoDaysBeforeMostRecent = d[d.length - 3];
  const threeDaysBeforeMostRecent = d[d.length - 4];

  const r = `${reportOne(dayBeforeMostRecent, mostRecentDay)}

${reportOne(twoDaysBeforeMostRecent, mostRecentDay)}

${reportOne(threeDaysBeforeMostRecent, mostRecentDay)}

FAQ
  Q: Which data?
  A: Data for just USA from https://covidtracking.com

  Q: What's up with "percent of newly tested people that have the virus"?
  A: In South Korea this number is about 1%. Ie. in South Korea 99% of people
     newly tested for covid don't have the virus. If America can get this
     number lower then that may be evidence that we are starting to control
     the virus.`;

  console.log(r);

  function renderOneDaysData(day) {
    return `${day.date} `
  }

  function reportOne(dayEarlier, dayLater) {
    const d = delta(dayEarlier, dayLater);
    return `For ${dayLater.date - dayEarlier.date} days ending ${dayLater.date}
  percent growth in total cumulative people with the virus: ${renderPercent(d.percentGrowthInPositive)}
  percent growth in total cumulative tests done to see if people have the virus: ${renderPercent(d.percentGrowthInTotalTests)}
  percent of newly tested people that have the virus: ${renderPercent(d.percentNewTestResultsThatArePositive)}`;
  }

  function renderPercent(pct) {
    return `${Math.round(pct * 1000) / 10}%`;
  }

  function delta(dayEarlier, dayLater) {
    const positiveDelta = dayLater.positive - dayEarlier.positive;
    const negativeDelta = dayLater.negative - dayEarlier.negative;
    const posNegDelta = dayLater.posNeg - dayEarlier.posNeg;
    const percentNewTestResultsThatArePositive = positiveDelta / posNegDelta;
    const percentGrowthInPositive = dayLater.positive / dayEarlier.positive - 1;
    const percentGrowthInTotalTests = dayLater.total / dayEarlier.total - 1;
    return {
      positiveDelta,
      negativeDelta,
      posNegDelta,
      percentNewTestResultsThatArePositive,
      percentGrowthInPositive,
      percentGrowthInTotalTests,
    };
  }
}

report();
